"""
Architect Agent for Bitty
Responsible for system design, tradeoff analysis, and technical specifications
"""

import logging
from typing import List, Dict, Any
from dataclasses import dataclass
from bitty.agent import BaseAgent


@dataclass
class DesignSpec:
    """Design specification generated by ArchitectAgent"""
    components: List[str]
    interfaces: Dict[str, str]
    diagrams: List[str]  # paths to generated diagrams (placeholder)
    notes: str


class ArchitectAgent(BaseAgent):
    """Creates high-level system designs based on tasks"""
    
    async def design(self, tasks: List[Any]) -> DesignSpec:
        self.logger.info("Architect designing system based on tasks")
        # Placeholder design: create a simple component list
        components = ["core", "api", "storage", "worker"]
        interfaces = {"core": "api", "api": "storage", "worker": "core"}
        diagrams = []  # could be generated later
        notes = "Generated design based on provided tasks"
        spec = DesignSpec(components=components, interfaces=interfaces, diagrams=diagrams, notes=notes)
        self.memory.store("design", spec)
        return spec
