pub mod attention;
pub mod context_memory;
pub mod encoding;
pub mod features;
pub mod hd;
pub mod hnsw;
pub mod hypervector;
pub mod memory;
pub mod reasoning;
pub mod routing;

pub use attention::SparseAttention;
pub use context_memory::{ChunkRecord, ContextMemory, ContextMemoryConfig};
pub use encoding::{encode_activation_direct, RandomIndexCodebook};
pub use features::FeatureExtractor;
pub use hd::{bind, bundle, encode_sequence, permute};
pub use hnsw::BitHNSW;
pub use hypervector::HyperVector;
pub use memory::SparseAssociativeMemory;
pub use reasoning::ReasoningUnit;
pub use routing::Router;
