//! Prometheus-format metrics for the inference server.
//!
//! Hand-rolled text exposition (Prometheus v0.0.4) so the server keeps its
//! dependency surface small: counters, gauges, and one latency histogram, all
//! stored behind atomics/mutexes and rendered on demand by the `/metrics`
//! endpoint.

use std::collections::HashMap;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Mutex;

/// Histogram bucket upper bounds, in seconds. The implicit final `+Inf` bucket
/// is the count of all observations, so it is not listed here.
pub(crate) const DURATION_BUCKETS: &[f64] = &[
    0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0,
];

/// Shared, cheap metric counters for the inference server.
#[derive(Default)]
pub struct Metrics {
    requests_total: Mutex<HashMap<String, u64>>,
    tokens_total: AtomicU64,
    requests_rejected: AtomicU64,
    swaps_total: AtomicU64,
    in_flight: AtomicU64,
    queue_depth: AtomicU64,
    queue_capacity: AtomicU64,
    duration_buckets: [AtomicU64; DURATION_BUCKETS.len()],
    duration_sum_us: AtomicU64,
    duration_count: AtomicU64,
}

impl Metrics {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn inc_requests(&self, endpoint: &str) {
        let mut m = self.requests_total.lock().unwrap();
        *m.entry(endpoint.to_string()).or_insert(0) += 1;
    }

    pub fn inc_tokens(&self, n: u64) {
        self.tokens_total.fetch_add(n, Ordering::Relaxed);
    }

    pub fn inc_rejected(&self) {
        self.requests_rejected.fetch_add(1, Ordering::Relaxed);
    }

    pub fn inc_swaps(&self) {
        self.swaps_total.fetch_add(1, Ordering::Relaxed);
    }

    pub fn in_flight_inc(&self) {
        self.in_flight.fetch_add(1, Ordering::Relaxed);
    }

    pub fn in_flight_dec(&self) {
        self.in_flight.fetch_sub(1, Ordering::Relaxed);
    }

    pub fn set_queue_depth(&self, depth: usize) {
        self.queue_depth.store(depth as u64, Ordering::Relaxed);
    }

    pub fn set_queue_capacity(&self, capacity: usize) {
        self.queue_capacity
            .store(capacity as u64, Ordering::Relaxed);
    }

    /// Record one completed request. `secs` is the wall-clock latency.
    pub fn observe_duration(&self, secs: f64) {
        let idx = DURATION_BUCKETS
            .iter()
            .position(|b| secs <= *b)
            .unwrap_or(DURATION_BUCKETS.len() - 1);
        self.duration_buckets[idx].fetch_add(1, Ordering::Relaxed);
        self.duration_sum_us
            .fetch_add((secs * 1e6) as u64, Ordering::Relaxed);
        self.duration_count.fetch_add(1, Ordering::Relaxed);
    }

    /// Render the registry in Prometheus text exposition format v0.0.4.
    pub fn render(&self) -> String {
        let mut out = String::new();

        out.push_str("# HELP bitllm_requests_total Inference requests received by endpoint\n");
        out.push_str("# TYPE bitllm_requests_total counter\n");
        let endpoints_guard = self.requests_total.lock().unwrap();
        let mut endpoints: Vec<(&String, &u64)> = endpoints_guard.iter().collect();
        endpoints.sort_by(|a, b| a.0.cmp(b.0));
        for (endpoint, count) in endpoints {
            out.push_str(&format!(
                "bitllm_requests_total{{endpoint=\"{endpoint}\"}} {count}\n"
            ));
        }

        out.push_str("# HELP bitllm_tokens_total Tokens generated by the model\n");
        out.push_str("# TYPE bitllm_tokens_total counter\n");
        out.push_str(&format!(
            "bitllm_tokens_total {}\n",
            self.tokens_total.load(Ordering::Relaxed)
        ));

        out.push_str(
            "# HELP bitllm_requests_rejected_total Requests rejected because the queue was full\n",
        );
        out.push_str("# TYPE bitllm_requests_rejected_total counter\n");
        out.push_str(&format!(
            "bitllm_requests_rejected_total {}\n",
            self.requests_rejected.load(Ordering::Relaxed)
        ));

        out.push_str("# HELP bitllm_model_swaps_total Model hot-swap operations completed\n");
        out.push_str("# TYPE bitllm_model_swaps_total counter\n");
        out.push_str(&format!(
            "bitllm_model_swaps_total {}\n",
            self.swaps_total.load(Ordering::Relaxed)
        ));

        out.push_str("# HELP bitllm_in_flight_requests Requests currently being served\n");
        out.push_str("# TYPE bitllm_in_flight_requests gauge\n");
        out.push_str(&format!(
            "bitllm_in_flight_requests {}\n",
            self.in_flight.load(Ordering::Relaxed)
        ));

        out.push_str("# HELP bitllm_queue_depth Inference queue depth\n");
        out.push_str("# TYPE bitllm_queue_depth gauge\n");
        out.push_str(&format!(
            "bitllm_queue_depth {}\n",
            self.queue_depth.load(Ordering::Relaxed)
        ));

        out.push_str("# HELP bitllm_queue_capacity Maximum inference queue depth\n");
        out.push_str("# TYPE bitllm_queue_capacity gauge\n");
        out.push_str(&format!(
            "bitllm_queue_capacity {}\n",
            self.queue_capacity.load(Ordering::Relaxed)
        ));

        out.push_str("# HELP bitllm_request_duration_seconds Request latency\n");
        out.push_str("# TYPE bitllm_request_duration_seconds histogram\n");
        let mut cum = 0u64;
        for (i, bucket) in DURATION_BUCKETS.iter().enumerate() {
            cum += self.duration_buckets[i].load(Ordering::Relaxed);
            out.push_str(&format!(
                "bitllm_request_duration_seconds_bucket{{le=\"{bucket}\"}} {cum}\n"
            ));
        }
        let count = self.duration_count.load(Ordering::Relaxed);
        out.push_str(&format!(
            "bitllm_request_duration_seconds_bucket{{le=\"+Inf\"}} {count}\n"
        ));
        out.push_str(&format!(
            "bitllm_request_duration_seconds_sum {:.6}\n",
            self.duration_sum_us.load(Ordering::Relaxed) as f64 / 1e6
        ));
        out.push_str(&format!("bitllm_request_duration_seconds_count {count}\n"));

        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_all_metric_families() {
        let m = Metrics::new();
        m.inc_requests("/v1/chat/completions");
        m.inc_requests("/v1/completions");
        m.inc_tokens(42);
        m.inc_rejected();
        m.set_queue_depth(3);
        m.set_queue_capacity(64);
        m.observe_duration(0.02);

        let out = m.render();
        assert!(out.contains("# TYPE bitllm_requests_total counter"));
        assert!(out.contains("bitllm_requests_total{endpoint=\"/v1/chat/completions\"} 1"));
        assert!(out.contains("bitllm_tokens_total 42"));
        assert!(out.contains("bitllm_requests_rejected_total 1"));
        assert!(out.contains("bitllm_queue_depth 3"));
        assert!(out.contains("bitllm_queue_capacity 64"));
        assert!(out.contains("bitllm_request_duration_seconds_bucket{le=\"0.05\"} 1"));
        assert!(out.contains("bitllm_request_duration_seconds_count 1"));
    }

    #[test]
    fn histogram_buckets_are_cumulative() {
        let m = Metrics::new();
        m.observe_duration(0.0001);
        m.observe_duration(0.02);
        m.observe_duration(100.0);
        let out = m.render();
        // 0.0001 -> le=0.001; 0.02 -> le=0.05; 100 -> only +Inf.
        assert!(out.contains("bitllm_request_duration_seconds_bucket{le=\"0.001\"} 1"));
        assert!(out.contains("bitllm_request_duration_seconds_bucket{le=\"0.05\"} 2"));
        assert!(out.contains("bitllm_request_duration_seconds_bucket{le=\"+Inf\"} 3"));
        assert!(out.contains("bitllm_request_duration_seconds_count 3"));
    }

    #[test]
    fn endpoints_rendered_sorted() {
        let m = Metrics::new();
        m.inc_requests("b");
        m.inc_requests("a");
        let out = m.render();
        let a = out.find("bitllm_requests_total{endpoint=\"a\"}").unwrap();
        let b = out.find("bitllm_requests_total{endpoint=\"b\"}").unwrap();
        assert!(a < b);
    }
}
